baseURL = 'https://xiang-zhang-98.github.io/'
languageCode = 'en-us'
title = "Xiang Zhang's Personal Homepage"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = "G-4KBSJL08XE"
enableRobotsTXT = true
copyright = "&copy; Copyright 2024, Xiang Zhang"

# Configuration Features
[params]
  description = "I’m a fifth-year Ph.D. student in Robotics at the University of California, Berkeley." 
  header_title = "Xiang Zhang"                 # Your header title
  header_subtitle = "Ph.D. Candidate @ UC Berkeley" # Your header subtitle
  header_email = "Email: xiang_zhang_98 [at] berkeley [dot] edu"
  home_image = "/images/xiang.jpg"          # Path to header image starting from the static directory (optional)
  recent_posts = 0                           # Max amount of recent posts to show
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"        # First-choice font
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-2x"
    href = "https://www.linkedin.com/in/xiang-zhang-b61a69227/"
  [[params.social]]
    fa_icon = "ai ai-google-scholar-square ai-2x"
    href = "https://scholar.google.com/citations?user=0hw9U38AAAAJ&hl=en&oi=sra"
